
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: nodejs-app
spec:
    type: NodePort
    selector:
        app: nodejs-app
    ports:
        - port: 8080
          targetPort: 8080
