apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodejs-app
spec:
    selector:
        matchLabels:
            app: nodejs-app
    replicas: 1
    template:
        metadata:
            labels:
                app: nodejs-app
        spec:
            containers:
                - name: nodejs-app
                  imagePullPolicy: Never
                  image: devopshint/node-app:latest
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: nodejs-app
spec:
    type: NodePort
    selector:
        app: nodejs-app
    ports:
        - port: 8080
          targetPort: 8080
