name: Minikube CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Minikube
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --config=minikube.yaml

    - name: Build and deploy your application
      run: |
        # Add your build and deployment commands here
        kubectl apply -f k8s-node-app.yaml
